version: '3'

services:
  expenses:
    image: 'rrromix/expenses:0.0.3'
    restart: always
    build:
      context: .
    container_name: expenses
    ports:
      - '8081:8080'
    depends_on:
      - wish_db
    environment:
      - spring.datasource.url=jdbc:postgresql://wish_db:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  wish_db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: wish_db
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  db-data: