# connect to database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wish_db
    username: postgres
    password: 321

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_batch_fetch_size: 50
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
#        show_sql: true
#        format_sql: true

  # DOESN'T WORK PROPERLY. NOW SET VALUES PROGRAMMATICALLY
  rabbitmq:
    host: rabbitmq
    port: 61613
    username: guest
    password: guest

  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    url: ${spring.datasource.url}
    locations: classpath:db.migration
    user: ${spring.datasource.username}
    enabled: true
    password: ${spring.datasource.password}
    baseline-on-migrate: true

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iterations: 64
      key_length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 86400000
  issuer: rrromix

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        messaging: DEBUG
#        web:
#          socket: DEBUG

#spring.web.resources.cache.period=0